// !! do not specify version in the shader this is done by the compiler !!
// This file includes common.glsl during compilation
#line 4

layout(local_size_x = 64) in;

void main() {
    // ====== Variable format: ======
    // c_ prefix for caster related variables, e.g. c_prim would be the triangle that is 
    //     casting light.
    // r_ prefix for receiver related variables, e.g. r_prim would be the triangle that is
    //     receiving light.
    // s_ prefix for shadow related variables, e.g. s_prim would be the triangle that is
    //     casting a shadow from the caster onto the receiver.
    // ==============================

    int primitiveID = int(gl_GlobalInvocationID.x);

    Triangle c_prim = get_primitive(primitiveID);


    // Access Material data (example)
    // Material material = materials[primitiveID]; // Uncomment this line if materials are needed

    // Access Lightmap data (example)
    // Lightmap lightmap = lightmaps[primitiveID]; // Uncomment this line if lightmaps are needed

    vec3 ex_dir = vec3(0.0, 0.0, 1.0);
    float cos_theta = dot(c_prim.normal, ex_dir);

    // normalize to 0-1
    cos_theta = (cos_theta + 1.0) / 2.0;

    material_buffer[primitiveID].emissive_strength = cos_theta;
}
