// !! do not specify version in the shader this is done by the compiler !!
// This file includes common.glsl during compilation
#line 4

layout(local_size_x = 64) in;

uniform int KS_CUR_BOUNCE;

// This is the main compute shader that does the ray tracing. There are two version, one that only
// traces from E (initially emissive set), so only surfaces with an emissive material, and another that
// only traces existing lightmaps. This just makes it way easier to deal with memory, logic, synch etc.

// This version is the one that traces only from existin lightmaps, and can be called multiple times
void main() {
    // ====== Variable format: ======
    // c_ prefix for caster related variables, e.g. c_prim would be the triangle that is 
    //     casting light.
    // r_ prefix for receiver related variables, e.g. r_prim would be the triangle that is
    //     receiving light.
    // s_ prefix for shadow related variables, e.g. s_prim would be the triangle that is
    //     casting a shadow from the caster onto the receiver.
    // ==============================

    // Loop over every potential caster and see if it affects us

    int r_primitiveID = int(gl_GlobalInvocationID.x);

    Lightmap r_lightmap = lightmap_buffer[r_primitiveID];

    // if we already have enough lights we can skip this primitive
    if (r_lightmap.numLights >= NUM_LIGHTS_PER_PRIMITIVE) {
		return;
    }

    Triangle r_prim = get_primitive(r_primitiveID);
    Material r_mat = material_buffer[r_primitiveID];
    
    
    for (int c_primitiveID = KS_NUM_PRIMITIVES; c_primitiveID >= 0; c_primitiveID--) {
        if (c_primitiveID == r_primitiveID) {
			continue;
		}

		Lightmap c_lightmap = lightmap_buffer[c_primitiveID];

        // unless the caster has >0 lights we can skip it
        if (c_lightmap.numLights <= 0) {
			continue;
		}

        Material c_mat = material_buffer[c_primitiveID];
        Triangle c_prim = get_primitive(c_primitiveID);

        // we have identified a potential caster now make sure that we are
        // not behind it. We cannot just throw out casters if we are facing the same way because
        // some part of it might still be visible
        // occlusion will be implemeneted later.

        // Has to be > 0 because i fucke dup
        bool is0behind = plane_sdf(r_prim.v0, c_prim) < 0.0;
        bool is1behind = plane_sdf(r_prim.v1, c_prim) < 0.0;
        bool is2behind = plane_sdf(r_prim.v2, c_prim) < 0.0;

        if (is0behind && is1behind && is2behind) {
            continue;
        }

        int light_idx_offset = NUM_LIGHTS_PER_PRIMITIVE * c_primitiveID;

        // Loop over every light and see if any of them should be traced onto us
        for (int c_lightIdx = 0; c_lightIdx <= c_lightmap.numLights; c_lightIdx++) {
            Light c_light = lights_buffer[light_idx_offset + c_lightIdx];

            // make sure we arent duplicating light
            if (c_light.bounce != KS_CUR_BOUNCE - 1) {
                continue;
            }

            // discard unimportant lights
            if (c_light.prevIntensity < light_min_intensity) {
                continue;
            }

            if (c_light.prevDist + pow(distance(r_prim.mean, c_prim.mean), 2) >= max_light_distance) {
                continue;
            }

            Material c_mat = material_buffer[c_primitiveID];

            Light newLight;
            newLight.casterIndex = c_primitiveID;
            newLight.bounce = KS_CUR_BOUNCE;
            // How big are we from the perspective of the caster

            // the solid angle of the reciever only matters when the reciever becomes the caster
            // in the next light bounce.
            newLight.thisIntensity = c_light.prevIntensity;

            newLight.prevIntensity = clamp(solid_angle(c_prim.mean, r_prim) / (2 * PI), 0, 1);
            newLight.prevIntensity *= c_light.prevIntensity; // intensity loss compounds

            // I should migrate colour to be a vec3
            vec3 c_mat_col = vec3(c_mat.color_r, c_mat.color_g, c_mat.color_b);
            newLight.tint = c_light.tint * c_mat_col;

            // Add previous distance for sequential convolution
            newLight.prevDist = c_light.prevDist + pow(distance(r_prim.mean, c_prim.mean), 2);

            newLight.ogCaster = c_light.ogCaster; // never changes

            int nextIdx = r_primitiveID * NUM_LIGHTS_PER_PRIMITIVE;
            nextIdx += r_lightmap.numLights;

            lights_buffer[nextIdx] = newLight;

            r_lightmap.numLights++;

            if (r_lightmap.numLights >= NUM_LIGHTS_PER_PRIMITIVE) {
			    break;
		    }
        }

        if (r_lightmap.numLights >= NUM_LIGHTS_PER_PRIMITIVE) {
            break;
        }
    }

    lightmap_buffer[r_primitiveID] = r_lightmap;

}
