// !! THIS FILE IS INCLUDED IN BOTH GLSL AND C++ CODE !!
// !! ALL DEFINITION MUST EITHER BE VALID IN BOTH LANGUAGES, THE GLSL IMPORTER 
// !! DOES NOT SUPPORT CONDITIONAL COMPILATION !!
#define EPSILON 0.0001

#define NUM_LIGHTS_PER_PRIMITIVE 10
#define NUM_SHADOWS_PER_PRIMITIVE 10